// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEnwC9Lzx-KO9V0AXCQsa2HDwAEVeEn9A',
    appId: '1:1078032412650:web:2b76b5f28d5c97dd710c93',
    messagingSenderId: '1078032412650',
    projectId: 'reddit-clone-8db5e',
    authDomain: 'reddit-clone-8db5e.firebaseapp.com',
    storageBucket: 'reddit-clone-8db5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnFH61Jfi4TLk0DDwDVSO5BuzIKWHvZNE',
    appId: '1:1078032412650:android:5c779e52cf3d7509710c93',
    messagingSenderId: '1078032412650',
    projectId: 'reddit-clone-8db5e',
    storageBucket: 'reddit-clone-8db5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCXSvax5QnHH9z24pNFuubfloTmrJGuVs',
    appId: '1:1078032412650:ios:907b6d6f3b7fc5e9710c93',
    messagingSenderId: '1078032412650',
    projectId: 'reddit-clone-8db5e',
    storageBucket: 'reddit-clone-8db5e.appspot.com',
    iosClientId: '1078032412650-bvo3vps4u25lrs05i9ojpfj3a1gdkfg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
